### ISSUE TITLE
Retrieving session cookies expires them

### ISSUE THREAD

**Issue by shoutizix** [thewh1teagle/rookie#8] opened 2023-10-09 07:37 UTC
Hello,

When using rookiepy to retrieve the sessionid cookie for a website, it directly expires the session, so I can't use it to login with my script. I use Microsoft Edge and the cookie expires when I use load() or edge() methods, even if I don't use the cookie in a request.

Is it a problem with rookiepy or with the website I'm trying to connect ? It's weird because with browser_cookie3, before the chromium update, it worked perfectly.

Thanks

**Comment by shoutizix** [comment] 2023-10-09 08:31
I'm sorry it was a problem on my side, not related to rookiepy !

**Comment by thewh1teagle** [comment] 2023-10-09 22:35
Thanks for letting me know!
Fixed in latest version.

**Comment by shoutizix** [comment] 2023-10-10 07:21
v0.2.9 hasn't fixed the problem for me. I use this code to retrieve cookies from a website :
```
cookies = rookiepy.edge([domain_name])
cj = rookiepy.to_cookiejar(cookies)
```
And then I use this cookiejar as my cookies for the session. This works but only 1 time, directly after the session's cookie is expired (as if I closed the browser), so I have to relogin on my browser everytime.
But when I'm manually retrieving the cookies via edge's inspector and setting them manually in my code, like this :
```
cj = requests.cookies.cookiejar_from_dict({})
cookie = requests.cookies.create_cookie('JSESSIONID', value_found_with_inspector, domain=domain, path='/eq', secure=True, expires=None)
cj.set_cookie(cookie)
```

It works and the session on my browser keeps logged in. Do you have an idea what could cause this ?

**Comment by thewh1teagle** [comment] 2023-10-10 09:51
1.Try to iterate the cookies and print their name and expires and paste here (don't paste values)


```
import rookiepy
cookies = rookiepy.edge()
for c in cookies:
  print(c['name'], c['expires'])
```
2. Try to confirm that the cookies isn't sent in the second try (don't paste result):
3. ```
session = ...
res = session.get(..., allow_redirect=False)
print(res.request.headers)
```

**Comment by shoutizix** [comment] 2023-10-10 11:46
Thank you for your answer ! In fact, even executing only the code from **1.** (Thus, no request) leads to the same problem for me, but here is the output :
```
eq_language 1726816242
JSESSIONID None
```
If I keep the inspector of the browser open on another screen while I'm executing the code from **1.** I can see the cookie JSESSIONID disappearing, then if I click on something on the webpage or if I refresh it, it tells me that the session has expired.

**Comment by thewh1teagle** [comment] 2023-10-10 13:03
The expire date of `en_language` looks ok (`2024`)
Tell me what browser you use, if you can also what's the website you use, 
as I understand your problem currently is that the JSESSIONID cookie dissapper from the cookies which `rookiepy` return only when you open the inspect element

**Comment by shoutizix** [comment] 2023-10-10 14:02
I'm using Microsoft Edge, but I can't tell you the website as it is internal in the company. 
No, I'm sorry if my previous explanation were not clear. 

`rookiepy` retrieves correctly the cookies (and I can use them in my requests), but the problem is when **JSESSIONID** is retrieved : it expires the session, so I have to reconnect again on Edge.

What I was mentioning in my previous comments was that I tried to retrieve the value of **JSESSIONID** using the inspector on Edge and in Python I create myself the cookie with the appropriate parameters (thus without using `rookiepy`). And this way I am able to make all the requests I want without causing my session on the Edge to expire.

The problem is that the user has to find the value of the cookie himself and enter it every time he uses my script. I would prefer that to be automatic that's why I used `browser_cookie3` and now `rookiepy`.

Maybe when `rookiepy` reads the cookies something detects it and make the session expired. Do you think it's possible ?

**Comment by guilhermecugler** [comment] 2023-10-17 04:47
> The values from `rookiepy` and `edge` are equal.
> 
> No, I didn't have this issue with `browser_cookie3` (before the chromium update)

I have the same problem, did you fixed it?

**Comment by thewh1teagle** [comment] 2023-10-17 09:41
@guilhermecugler 
I didn't fixed it yey, because I can't reproduce it
Can you tell me how to?

**Comment by guilhermecugler** [comment] 2023-10-17 11:33
> @guilhermecugler I didn't fixed it yey, because I can't reproduce it Can you tell me how to?

I SOLVED...

When I do something like this:

```
cookies_painel = chrome(["site.net"])
cj = to_cookiejar(cookies_painel)

cookies = {}


for cookie in cj:
    items = {cookie.name: cookie.value}
    cookies.update(cookies)
    print(cookies)
```
  
the cookie SESSION is deleted and I cant use it anymore

I fixed using doing this:
```
import httpx

cookies_painel = chrome(["site.net"])
cj = to_cookiejar(cookies_painel)

cookies = httpx.Cookies()

for cookie in cj:
    cookies.set(cookie.name, cookie.value)
```

**Comment by thewh1teagle** [comment] 2023-10-18 00:04
Thank you for update!
So it looks like the problem is not in the browser, but in Python itself, 
The cookie jar object cause some cookies tk be expired. 
But @shoutizix told me first that the cookie is expire in the browser itself

**Comment by shoutizix** [comment] 2023-10-19 12:21
@thewh1teagle 
Yes, after executing the code (even just one line with ``` rookiepy.load(["site.net"]) ```), it causes the cookie to be expired thus the cookie is expired also in the browser.

**Comment by thewh1teagle** [comment] 2023-10-19 13:52
@shoutizix 
You right I can see that the session cookies disapper after we retrive them using `rookiepy`
The reason for that is because on `windows` `chrome` have a security feature which prevent other processes from reading the cookies file, by locking the file.
To bypass this restriction we unlock the file locking by forcing chrome process to seamlessly restart (using `restart-manager` api), same as `windows update` does.

Because the process is restarted the session cookies are expires.
But the cookies should loaded to your `Python` code, so it will only expire in the browser but you will still be able to use them from `Python`

**Comment by thewh1teagle** [comment] 2023-10-19 13:59
For instance in the library `browser_cookie3` it will throw an error because the cookies file lock
![image](https://github.com/thewh1teagle/rookie/assets/61390950/b7bf8b00-1e9f-47dd-9d14-04f8d7e4c298)

**Comment by thewh1teagle** [comment] 2023-10-22 01:57
I'm bot sure it's possible,
And if so, it will be super hacky and can be harmful to the cookies file
Because it doesn't recommend to write to the same sqlite from two different places at the same time.

But I may have another solution for you
What about starting the browser with the file locking disabled? 
This way it will retrieve the cookie and they will remain there because we won't need to restart the browser to unlock the file.

**Closed** 2023-10-23 07:58 UTC
Labels: bug
